
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

package com.example.pkm_forms.Analizadores.Forms;

import java_cup.runtime.Symbol;
import com.example.pkm_forms.Models.*;
import com.example.pkm_forms.Patron.Instruction;
import com.example.pkm_forms.Expression.Aritmeticos.Division;
import com.example.pkm_forms.Expression.Aritmeticos.Multiplicacion;
import com.example.pkm_forms.Expression.Aritmeticos.Modulo;
import com.example.pkm_forms.Expression.Aritmeticos.Potenciacion;
import com.example.pkm_forms.Expression.Aritmeticos.Resta;
import com.example.pkm_forms.Expression.Aritmeticos.Suma;
import com.example.pkm_forms.Expression.Aritmeticos.NegacionAritmetica;
import com.example.pkm_forms.Expression.Native;
import com.example.pkm_forms.Instruction.Variable.*;
import com.example.pkm_forms.Instruction.Print;
import java.util.List;
import java.util.ArrayList;
import java.util.LinkedList;
import java_cup.runtime.XMLElement;

/** CUP v0.11b 20160615 (GIT 4ac7450) generated parser.
  */
@SuppressWarnings({"rawtypes"})
public class ParserForms extends java_cup.runtime.lr_parser {

 public final Class getSymbolContainer() {
    return sym.class;
}

  /** Default constructor. */
  @Deprecated
  public ParserForms() {super();}

  /** Constructor which sets the default scanner. */
  @Deprecated
  public ParserForms(java_cup.runtime.Scanner s) {super(s);}

  /** Constructor which sets the default scanner. */
  public ParserForms(java_cup.runtime.Scanner s, java_cup.runtime.SymbolFactory sf) {super(s,sf);}

  /** Production table. */
  protected static final short _production_table[][] = 
    unpackFromStrings(new String[] {
    "\000\037\000\002\002\004\000\002\002\003\000\002\003" +
    "\004\000\002\003\003\000\002\004\003\000\002\004\003" +
    "\000\002\004\003\000\002\007\006\000\002\007\004\000" +
    "\002\007\006\000\002\007\004\000\002\017\005\000\002" +
    "\005\004\000\002\016\003\000\002\016\003\000\002\010" +
    "\004\000\002\010\005\000\002\010\005\000\002\010\003" +
    "\000\002\011\005\000\002\011\005\000\002\011\003\000" +
    "\002\012\005\000\002\012\005\000\002\012\003\000\002" +
    "\013\005\000\002\013\003\000\002\015\003\000\002\014" +
    "\003\000\002\014\003\000\002\014\003" });

  /** Access to production table. */
  public short[][] production_table() {return _production_table;}

  /** Parse-action table. */
  protected static final short[][] _action_table = 
    unpackFromStrings(new String[] {
    "\000\061\000\012\004\007\005\013\125\015\144\010\001" +
    "\002\000\014\002\ufffe\004\ufffe\005\ufffe\125\ufffe\144\ufffe" +
    "\001\002\000\014\002\ufffd\004\ufffd\005\ufffd\125\ufffd\144" +
    "\ufffd\001\002\000\014\002\ufffc\004\ufffc\005\ufffc\125\ufffc" +
    "\144\ufffc\001\002\000\004\125\061\001\002\000\016\071" +
    "\026\076\027\123\025\124\017\125\030\126\053\001\002" +
    "\000\014\002\000\004\007\005\013\125\015\144\010\001" +
    "\002\000\014\002\ufffb\004\ufffb\005\ufffb\125\ufffb\144\ufffb" +
    "\001\002\000\004\125\051\001\002\000\004\002\050\001" +
    "\002\000\004\113\016\001\002\000\014\071\026\076\027" +
    "\123\025\124\017\125\030\001\002\000\032\002\uffe4\004" +
    "\uffe4\005\uffe4\070\uffe4\071\uffe4\072\uffe4\073\uffe4\074\uffe4" +
    "\075\uffe4\077\uffe4\125\uffe4\144\uffe4\001\002\000\020\002" +
    "\ufff6\004\ufff6\005\ufff6\070\034\071\032\125\ufff6\144\ufff6" +
    "\001\002\000\032\002\uffe7\004\uffe7\005\uffe7\070\uffe7\071" +
    "\uffe7\072\uffe7\073\uffe7\074\uffe7\075\uffe7\077\uffe7\125\uffe7" +
    "\144\uffe7\001\002\000\032\002\uffe9\004\uffe9\005\uffe9\070" +
    "\uffe9\071\uffe9\072\uffe9\073\uffe9\074\uffe9\075\uffe9\077\uffe9" +
    "\125\uffe9\144\uffe9\001\002\000\032\002\uffec\004\uffec\005" +
    "\uffec\070\uffec\071\uffec\072\uffec\073\uffec\074\042\075\041" +
    "\077\uffec\125\uffec\144\uffec\001\002\000\026\002\uffef\004" +
    "\uffef\005\uffef\070\uffef\071\uffef\072\037\073\036\077\uffef" +
    "\125\uffef\144\uffef\001\002\000\032\002\uffe3\004\uffe3\005" +
    "\uffe3\070\uffe3\071\uffe3\072\uffe3\073\uffe3\074\uffe3\075\uffe3" +
    "\077\uffe3\125\uffe3\144\uffe3\001\002\000\014\071\026\076" +
    "\027\123\025\124\017\125\030\001\002\000\014\071\026" +
    "\076\027\123\025\124\017\125\030\001\002\000\032\002" +
    "\uffe5\004\uffe5\005\uffe5\070\uffe5\071\uffe5\072\uffe5\073\uffe5" +
    "\074\uffe5\075\uffe5\077\uffe5\125\uffe5\144\uffe5\001\002\000" +
    "\010\070\034\071\032\077\033\001\002\000\012\076\027" +
    "\123\025\124\017\125\030\001\002\000\032\002\uffe8\004" +
    "\uffe8\005\uffe8\070\uffe8\071\uffe8\072\uffe8\073\uffe8\074\uffe8" +
    "\075\uffe8\077\uffe8\125\uffe8\144\uffe8\001\002\000\012\076" +
    "\027\123\025\124\017\125\030\001\002\000\026\002\ufff1" +
    "\004\ufff1\005\ufff1\070\ufff1\071\ufff1\072\037\073\036\077" +
    "\ufff1\125\ufff1\144\ufff1\001\002\000\012\076\027\123\025" +
    "\124\017\125\030\001\002\000\012\076\027\123\025\124" +
    "\017\125\030\001\002\000\032\002\uffed\004\uffed\005\uffed" +
    "\070\uffed\071\uffed\072\uffed\073\uffed\074\042\075\041\077" +
    "\uffed\125\uffed\144\uffed\001\002\000\012\076\027\123\025" +
    "\124\017\125\030\001\002\000\012\076\027\123\025\124" +
    "\017\125\030\001\002\000\032\002\uffeb\004\uffeb\005\uffeb" +
    "\070\uffeb\071\uffeb\072\uffeb\073\uffeb\074\uffeb\075\uffeb\077" +
    "\uffeb\125\uffeb\144\uffeb\001\002\000\032\002\uffea\004\uffea" +
    "\005\uffea\070\uffea\071\uffea\072\uffea\073\uffea\074\uffea\075" +
    "\uffea\077\uffea\125\uffea\144\uffea\001\002\000\032\002\uffee" +
    "\004\uffee\005\uffee\070\uffee\071\uffee\072\uffee\073\uffee\074" +
    "\042\075\041\077\uffee\125\uffee\144\uffee\001\002\000\026" +
    "\002\ufff0\004\ufff0\005\ufff0\070\ufff0\071\ufff0\072\037\073" +
    "\036\077\ufff0\125\ufff0\144\ufff0\001\002\000\022\002\ufff2" +
    "\004\ufff2\005\ufff2\070\ufff2\071\ufff2\077\ufff2\125\ufff2\144" +
    "\ufff2\001\002\000\004\002\001\001\002\000\016\002\ufff7" +
    "\004\ufff7\005\ufff7\113\052\125\ufff7\144\ufff7\001\002\000" +
    "\004\126\053\001\002\000\014\002\uffe6\004\uffe6\005\uffe6" +
    "\125\uffe6\144\uffe6\001\002\000\014\002\ufff8\004\ufff8\005" +
    "\ufff8\125\ufff8\144\ufff8\001\002\000\014\002\uffff\004\uffff" +
    "\005\uffff\125\uffff\144\uffff\001\002\000\020\002\ufff4\004" +
    "\ufff4\005\ufff4\070\034\071\032\125\ufff4\144\ufff4\001\002" +
    "\000\014\002\ufff5\004\ufff5\005\ufff5\125\ufff5\144\ufff5\001" +
    "\002\000\014\002\ufff3\004\ufff3\005\ufff3\125\ufff3\144\ufff3" +
    "\001\002\000\016\002\ufff9\004\ufff9\005\ufff9\113\062\125" +
    "\ufff9\144\ufff9\001\002\000\014\071\026\076\027\123\025" +
    "\124\017\125\030\001\002\000\020\002\ufffa\004\ufffa\005" +
    "\ufffa\070\034\071\032\125\ufffa\144\ufffa\001\002" });

  /** Access to parse-action table. */
  public short[][] action_table() {return _action_table;}

  /** <code>reduce_goto</code> table. */
  protected static final short[][] _reduce_table = 
    unpackFromStrings(new String[] {
    "\000\061\000\016\002\013\003\010\004\003\005\004\007" +
    "\005\017\011\001\001\000\002\001\001\000\002\001\001" +
    "\000\002\001\001\000\002\001\001\000\020\010\055\011" +
    "\023\012\022\013\021\014\020\015\057\016\056\001\001" +
    "\000\012\004\054\005\004\007\005\017\011\001\001\000" +
    "\002\001\001\000\002\001\001\000\002\001\001\000\002" +
    "\001\001\000\014\010\017\011\023\012\022\013\021\014" +
    "\020\001\001\000\002\001\001\000\002\001\001\000\002" +
    "\001\001\000\002\001\001\000\002\001\001\000\002\001" +
    "\001\000\002\001\001\000\014\010\046\011\023\012\022" +
    "\013\021\014\020\001\001\000\014\010\030\011\023\012" +
    "\022\013\021\014\020\001\001\000\002\001\001\000\002" +
    "\001\001\000\012\011\045\012\022\013\021\014\020\001" +
    "\001\000\002\001\001\000\012\011\034\012\022\013\021" +
    "\014\020\001\001\000\002\001\001\000\010\012\044\013" +
    "\021\014\020\001\001\000\010\012\037\013\021\014\020" +
    "\001\001\000\002\001\001\000\006\013\043\014\020\001" +
    "\001\000\006\013\042\014\020\001\001\000\002\001\001" +
    "\000\002\001\001\000\002\001\001\000\002\001\001\000" +
    "\002\001\001\000\002\001\001\000\002\001\001\000\004" +
    "\015\053\001\001\000\002\001\001\000\002\001\001\000" +
    "\002\001\001\000\002\001\001\000\002\001\001\000\002" +
    "\001\001\000\002\001\001\000\014\010\062\011\023\012" +
    "\022\013\021\014\020\001\001\000\002\001\001" });

  /** Access to <code>reduce_goto</code> table. */
  public short[][] reduce_table() {return _reduce_table;}

  /** Instance of action encapsulation class. */
  protected CUP$ParserForms$actions action_obj;

  /** Action encapsulation object initializer. */
  protected void init_actions()
    {
      action_obj = new CUP$ParserForms$actions(this);
    }

  /** Invoke a user supplied parse action. */
  public java_cup.runtime.Symbol do_action(
    int                        act_num,
    java_cup.runtime.lr_parser parser,
    java.util.Stack            stack,
    int                        top)
    throws java.lang.Exception
  {
    /* call code in generated class */
    return action_obj.CUP$ParserForms$do_action(act_num, parser, stack, top);
  }

  /** Indicates start state. */
  public int start_state() {return 0;}
  /** Indicates start production. */
  public int start_production() {return 0;}

  /** <code>EOF</code> Symbol index. */
  public int EOF_sym() {return 0;}

  /** <code>error</code> Symbol index. */
  public int error_sym() {return 1;}



/*
    //Listas para guardar Errores sintacticos
    Parser s;
    Parser(Parser s){this.s = s;}

    public LinkedList<SintaxError> listErrorSintactico = new LinkedList<>();

    public void syntax_error(Symbol s){
        listErrorSintactico.add(new SintaxError("Error de sintaxis recuperable", "No se esperaba: " +s.value, s.left, s.right));
    }

    public void unrecovered_syntax_(Symbol s) throws java.lang.Exception{
        listErrorSintactico.add(new SintaxError("Error de sintaxis no recuperable", "No se esperaba: " +s.value, s.left, s.right));
    }*/


/** Cup generated class to encapsulate user supplied action code.*/
@SuppressWarnings({"rawtypes", "unchecked", "unused"})
class CUP$ParserForms$actions {



    String console = "";


  private final ParserForms parser;

  /** Constructor */
  CUP$ParserForms$actions(ParserForms parser) {
    this.parser = parser;
  }

  /** Method 0 with the actual generated action code for actions 0 to 300. */
  public final java_cup.runtime.Symbol CUP$ParserForms$do_action_part00000000(
    int                        CUP$ParserForms$act_num,
    java_cup.runtime.lr_parser CUP$ParserForms$parser,
    java.util.Stack            CUP$ParserForms$stack,
    int                        CUP$ParserForms$top)
    throws java.lang.Exception
    {
      /* Symbol object for return from actions */
      java_cup.runtime.Symbol CUP$ParserForms$result;

      /* select the action based on the action number */
      switch (CUP$ParserForms$act_num)
        {
          /*. . . . . . . . . . . . . . . . . . . .*/
          case 0: // $START ::= initiation EOF 
            {
              Object RESULT =null;
		int start_valleft = ((java_cup.runtime.Symbol)CUP$ParserForms$stack.elementAt(CUP$ParserForms$top-1)).left;
		int start_valright = ((java_cup.runtime.Symbol)CUP$ParserForms$stack.elementAt(CUP$ParserForms$top-1)).right;
		LinkedList<Instruction> start_val = (LinkedList<Instruction>)((java_cup.runtime.Symbol) CUP$ParserForms$stack.elementAt(CUP$ParserForms$top-1)).value;
		RESULT = start_val;
              CUP$ParserForms$result = parser.getSymbolFactory().newSymbol("$START",0, ((java_cup.runtime.Symbol)CUP$ParserForms$stack.elementAt(CUP$ParserForms$top-1)), ((java_cup.runtime.Symbol)CUP$ParserForms$stack.peek()), RESULT);
            }
          /* ACCEPT */
          CUP$ParserForms$parser.done_parsing();
          return CUP$ParserForms$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 1: // initiation ::= instructions 
            {
              LinkedList<Instruction> RESULT =null;
		int aleft = ((java_cup.runtime.Symbol)CUP$ParserForms$stack.peek()).left;
		int aright = ((java_cup.runtime.Symbol)CUP$ParserForms$stack.peek()).right;
		LinkedList<Instruction> a = (LinkedList<Instruction>)((java_cup.runtime.Symbol) CUP$ParserForms$stack.peek()).value;
		 RESULT = a; 
              CUP$ParserForms$result = parser.getSymbolFactory().newSymbol("initiation",0, ((java_cup.runtime.Symbol)CUP$ParserForms$stack.peek()), ((java_cup.runtime.Symbol)CUP$ParserForms$stack.peek()), RESULT);
            }
          return CUP$ParserForms$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 2: // instructions ::= instructions instruction 
            {
              LinkedList<Instruction> RESULT =null;
		int aleft = ((java_cup.runtime.Symbol)CUP$ParserForms$stack.elementAt(CUP$ParserForms$top-1)).left;
		int aright = ((java_cup.runtime.Symbol)CUP$ParserForms$stack.elementAt(CUP$ParserForms$top-1)).right;
		LinkedList<Instruction> a = (LinkedList<Instruction>)((java_cup.runtime.Symbol) CUP$ParserForms$stack.elementAt(CUP$ParserForms$top-1)).value;
		int bleft = ((java_cup.runtime.Symbol)CUP$ParserForms$stack.peek()).left;
		int bright = ((java_cup.runtime.Symbol)CUP$ParserForms$stack.peek()).right;
		Instruction b = (Instruction)((java_cup.runtime.Symbol) CUP$ParserForms$stack.peek()).value;
		 RESULT = a; RESULT.add(b); 
              CUP$ParserForms$result = parser.getSymbolFactory().newSymbol("instructions",1, ((java_cup.runtime.Symbol)CUP$ParserForms$stack.elementAt(CUP$ParserForms$top-1)), ((java_cup.runtime.Symbol)CUP$ParserForms$stack.peek()), RESULT);
            }
          return CUP$ParserForms$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 3: // instructions ::= instruction 
            {
              LinkedList<Instruction> RESULT =null;
		int aleft = ((java_cup.runtime.Symbol)CUP$ParserForms$stack.peek()).left;
		int aright = ((java_cup.runtime.Symbol)CUP$ParserForms$stack.peek()).right;
		Instruction a = (Instruction)((java_cup.runtime.Symbol) CUP$ParserForms$stack.peek()).value;
		 RESULT = new LinkedList<Instruction>(); RESULT.add(a); 
              CUP$ParserForms$result = parser.getSymbolFactory().newSymbol("instructions",1, ((java_cup.runtime.Symbol)CUP$ParserForms$stack.peek()), ((java_cup.runtime.Symbol)CUP$ParserForms$stack.peek()), RESULT);
            }
          return CUP$ParserForms$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 4: // instruction ::= print 
            {
              Instruction RESULT =null;
		int aleft = ((java_cup.runtime.Symbol)CUP$ParserForms$stack.peek()).left;
		int aright = ((java_cup.runtime.Symbol)CUP$ParserForms$stack.peek()).right;
		Instruction a = (Instruction)((java_cup.runtime.Symbol) CUP$ParserForms$stack.peek()).value;
		 RESULT = a; 
              CUP$ParserForms$result = parser.getSymbolFactory().newSymbol("instruction",2, ((java_cup.runtime.Symbol)CUP$ParserForms$stack.peek()), ((java_cup.runtime.Symbol)CUP$ParserForms$stack.peek()), RESULT);
            }
          return CUP$ParserForms$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 5: // instruction ::= declaration 
            {
              Instruction RESULT =null;
		int aleft = ((java_cup.runtime.Symbol)CUP$ParserForms$stack.peek()).left;
		int aright = ((java_cup.runtime.Symbol)CUP$ParserForms$stack.peek()).right;
		Instruction a = (Instruction)((java_cup.runtime.Symbol) CUP$ParserForms$stack.peek()).value;
		 RESULT = a; 
              CUP$ParserForms$result = parser.getSymbolFactory().newSymbol("instruction",2, ((java_cup.runtime.Symbol)CUP$ParserForms$stack.peek()), ((java_cup.runtime.Symbol)CUP$ParserForms$stack.peek()), RESULT);
            }
          return CUP$ParserForms$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 6: // instruction ::= asignacion_variables 
            {
              Instruction RESULT =null;
		int aleft = ((java_cup.runtime.Symbol)CUP$ParserForms$stack.peek()).left;
		int aright = ((java_cup.runtime.Symbol)CUP$ParserForms$stack.peek()).right;
		Instruction a = (Instruction)((java_cup.runtime.Symbol) CUP$ParserForms$stack.peek()).value;
		 RESULT = a; 
              CUP$ParserForms$result = parser.getSymbolFactory().newSymbol("instruction",2, ((java_cup.runtime.Symbol)CUP$ParserForms$stack.peek()), ((java_cup.runtime.Symbol)CUP$ParserForms$stack.peek()), RESULT);
            }
          return CUP$ParserForms$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 7: // declaration ::= NUMBER IDENTIFICADOR IGUAL expresion_math 
            {
              Instruction RESULT =null;
		int aleft = ((java_cup.runtime.Symbol)CUP$ParserForms$stack.elementAt(CUP$ParserForms$top-2)).left;
		int aright = ((java_cup.runtime.Symbol)CUP$ParserForms$stack.elementAt(CUP$ParserForms$top-2)).right;
		Object a = (Object)((java_cup.runtime.Symbol) CUP$ParserForms$stack.elementAt(CUP$ParserForms$top-2)).value;
		int bleft = ((java_cup.runtime.Symbol)CUP$ParserForms$stack.peek()).left;
		int bright = ((java_cup.runtime.Symbol)CUP$ParserForms$stack.peek()).right;
		Instruction b = (Instruction)((java_cup.runtime.Symbol) CUP$ParserForms$stack.peek()).value;
		 RESULT = new Declaration((String) a, b, aleft, aright); 
              CUP$ParserForms$result = parser.getSymbolFactory().newSymbol("declaration",5, ((java_cup.runtime.Symbol)CUP$ParserForms$stack.elementAt(CUP$ParserForms$top-3)), ((java_cup.runtime.Symbol)CUP$ParserForms$stack.peek()), RESULT);
            }
          return CUP$ParserForms$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 8: // declaration ::= NUMBER IDENTIFICADOR 
            {
              Instruction RESULT =null;
		int aleft = ((java_cup.runtime.Symbol)CUP$ParserForms$stack.peek()).left;
		int aright = ((java_cup.runtime.Symbol)CUP$ParserForms$stack.peek()).right;
		Object a = (Object)((java_cup.runtime.Symbol) CUP$ParserForms$stack.peek()).value;
		 RESULT = new DeclarationDefault("number", (String) a, aleft, aright); 
              CUP$ParserForms$result = parser.getSymbolFactory().newSymbol("declaration",5, ((java_cup.runtime.Symbol)CUP$ParserForms$stack.elementAt(CUP$ParserForms$top-1)), ((java_cup.runtime.Symbol)CUP$ParserForms$stack.peek()), RESULT);
            }
          return CUP$ParserForms$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 9: // declaration ::= STRING IDENTIFICADOR IGUAL guardado_texto 
            {
              Instruction RESULT =null;
		int aleft = ((java_cup.runtime.Symbol)CUP$ParserForms$stack.elementAt(CUP$ParserForms$top-2)).left;
		int aright = ((java_cup.runtime.Symbol)CUP$ParserForms$stack.elementAt(CUP$ParserForms$top-2)).right;
		Object a = (Object)((java_cup.runtime.Symbol) CUP$ParserForms$stack.elementAt(CUP$ParserForms$top-2)).value;
		int bleft = ((java_cup.runtime.Symbol)CUP$ParserForms$stack.peek()).left;
		int bright = ((java_cup.runtime.Symbol)CUP$ParserForms$stack.peek()).right;
		Instruction b = (Instruction)((java_cup.runtime.Symbol) CUP$ParserForms$stack.peek()).value;
		 RESULT = new Declaration((String) a, b, aleft, aright); 
              CUP$ParserForms$result = parser.getSymbolFactory().newSymbol("declaration",5, ((java_cup.runtime.Symbol)CUP$ParserForms$stack.elementAt(CUP$ParserForms$top-3)), ((java_cup.runtime.Symbol)CUP$ParserForms$stack.peek()), RESULT);
            }
          return CUP$ParserForms$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 10: // declaration ::= STRING IDENTIFICADOR 
            {
              Instruction RESULT =null;
		int aleft = ((java_cup.runtime.Symbol)CUP$ParserForms$stack.peek()).left;
		int aright = ((java_cup.runtime.Symbol)CUP$ParserForms$stack.peek()).right;
		Object a = (Object)((java_cup.runtime.Symbol) CUP$ParserForms$stack.peek()).value;
		 RESULT = new DeclarationDefault("string", (String) a, aleft, aright); 
              CUP$ParserForms$result = parser.getSymbolFactory().newSymbol("declaration",5, ((java_cup.runtime.Symbol)CUP$ParserForms$stack.elementAt(CUP$ParserForms$top-1)), ((java_cup.runtime.Symbol)CUP$ParserForms$stack.peek()), RESULT);
            }
          return CUP$ParserForms$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 11: // asignacion_variables ::= IDENTIFICADOR IGUAL expresion_math 
            {
              Instruction RESULT =null;
		int aleft = ((java_cup.runtime.Symbol)CUP$ParserForms$stack.elementAt(CUP$ParserForms$top-2)).left;
		int aright = ((java_cup.runtime.Symbol)CUP$ParserForms$stack.elementAt(CUP$ParserForms$top-2)).right;
		Object a = (Object)((java_cup.runtime.Symbol) CUP$ParserForms$stack.elementAt(CUP$ParserForms$top-2)).value;
		int bleft = ((java_cup.runtime.Symbol)CUP$ParserForms$stack.peek()).left;
		int bright = ((java_cup.runtime.Symbol)CUP$ParserForms$stack.peek()).right;
		Instruction b = (Instruction)((java_cup.runtime.Symbol) CUP$ParserForms$stack.peek()).value;
		 RESULT = new Asignacion((String) a, b, aleft, aright); 
              CUP$ParserForms$result = parser.getSymbolFactory().newSymbol("asignacion_variables",13, ((java_cup.runtime.Symbol)CUP$ParserForms$stack.elementAt(CUP$ParserForms$top-2)), ((java_cup.runtime.Symbol)CUP$ParserForms$stack.peek()), RESULT);
            }
          return CUP$ParserForms$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 12: // print ::= MOSTRAR extra_print 
            {
              Instruction RESULT =null;
		int aleft = ((java_cup.runtime.Symbol)CUP$ParserForms$stack.peek()).left;
		int aright = ((java_cup.runtime.Symbol)CUP$ParserForms$stack.peek()).right;
		Instruction a = (Instruction)((java_cup.runtime.Symbol) CUP$ParserForms$stack.peek()).value;
		 RESULT = a; 
              CUP$ParserForms$result = parser.getSymbolFactory().newSymbol("print",3, ((java_cup.runtime.Symbol)CUP$ParserForms$stack.elementAt(CUP$ParserForms$top-1)), ((java_cup.runtime.Symbol)CUP$ParserForms$stack.peek()), RESULT);
            }
          return CUP$ParserForms$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 13: // extra_print ::= expresion_math 
            {
              Instruction RESULT =null;
		int aleft = ((java_cup.runtime.Symbol)CUP$ParserForms$stack.peek()).left;
		int aright = ((java_cup.runtime.Symbol)CUP$ParserForms$stack.peek()).right;
		Instruction a = (Instruction)((java_cup.runtime.Symbol) CUP$ParserForms$stack.peek()).value;
		 RESULT = new Print(a, aleft, aright); 
              CUP$ParserForms$result = parser.getSymbolFactory().newSymbol("extra_print",12, ((java_cup.runtime.Symbol)CUP$ParserForms$stack.peek()), ((java_cup.runtime.Symbol)CUP$ParserForms$stack.peek()), RESULT);
            }
          return CUP$ParserForms$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 14: // extra_print ::= guardado_texto 
            {
              Instruction RESULT =null;
		int aleft = ((java_cup.runtime.Symbol)CUP$ParserForms$stack.peek()).left;
		int aright = ((java_cup.runtime.Symbol)CUP$ParserForms$stack.peek()).right;
		Instruction a = (Instruction)((java_cup.runtime.Symbol) CUP$ParserForms$stack.peek()).value;
		 RESULT = new Print(a, aleft, aright); 
              CUP$ParserForms$result = parser.getSymbolFactory().newSymbol("extra_print",12, ((java_cup.runtime.Symbol)CUP$ParserForms$stack.peek()), ((java_cup.runtime.Symbol)CUP$ParserForms$stack.peek()), RESULT);
            }
          return CUP$ParserForms$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 15: // expresion_math ::= RESTA expresion_math 
            {
              Instruction RESULT =null;
		int aleft = ((java_cup.runtime.Symbol)CUP$ParserForms$stack.peek()).left;
		int aright = ((java_cup.runtime.Symbol)CUP$ParserForms$stack.peek()).right;
		Instruction a = (Instruction)((java_cup.runtime.Symbol) CUP$ParserForms$stack.peek()).value;
		 RESULT  = new NegacionAritmetica(a, aleft, aright); 
              CUP$ParserForms$result = parser.getSymbolFactory().newSymbol("expresion_math",6, ((java_cup.runtime.Symbol)CUP$ParserForms$stack.elementAt(CUP$ParserForms$top-1)), ((java_cup.runtime.Symbol)CUP$ParserForms$stack.peek()), RESULT);
            }
          return CUP$ParserForms$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 16: // expresion_math ::= expresion_math SUMA expresion_math_1 
            {
              Instruction RESULT =null;
		int aleft = ((java_cup.runtime.Symbol)CUP$ParserForms$stack.elementAt(CUP$ParserForms$top-2)).left;
		int aright = ((java_cup.runtime.Symbol)CUP$ParserForms$stack.elementAt(CUP$ParserForms$top-2)).right;
		Instruction a = (Instruction)((java_cup.runtime.Symbol) CUP$ParserForms$stack.elementAt(CUP$ParserForms$top-2)).value;
		int bleft = ((java_cup.runtime.Symbol)CUP$ParserForms$stack.peek()).left;
		int bright = ((java_cup.runtime.Symbol)CUP$ParserForms$stack.peek()).right;
		Instruction b = (Instruction)((java_cup.runtime.Symbol) CUP$ParserForms$stack.peek()).value;
		 RESULT  = new Suma(a, b, aleft, aright); 
              CUP$ParserForms$result = parser.getSymbolFactory().newSymbol("expresion_math",6, ((java_cup.runtime.Symbol)CUP$ParserForms$stack.elementAt(CUP$ParserForms$top-2)), ((java_cup.runtime.Symbol)CUP$ParserForms$stack.peek()), RESULT);
            }
          return CUP$ParserForms$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 17: // expresion_math ::= expresion_math RESTA expresion_math_1 
            {
              Instruction RESULT =null;
		int aleft = ((java_cup.runtime.Symbol)CUP$ParserForms$stack.elementAt(CUP$ParserForms$top-2)).left;
		int aright = ((java_cup.runtime.Symbol)CUP$ParserForms$stack.elementAt(CUP$ParserForms$top-2)).right;
		Instruction a = (Instruction)((java_cup.runtime.Symbol) CUP$ParserForms$stack.elementAt(CUP$ParserForms$top-2)).value;
		int bleft = ((java_cup.runtime.Symbol)CUP$ParserForms$stack.peek()).left;
		int bright = ((java_cup.runtime.Symbol)CUP$ParserForms$stack.peek()).right;
		Instruction b = (Instruction)((java_cup.runtime.Symbol) CUP$ParserForms$stack.peek()).value;
		 RESULT = new Resta(a, b, aleft, aright); 
              CUP$ParserForms$result = parser.getSymbolFactory().newSymbol("expresion_math",6, ((java_cup.runtime.Symbol)CUP$ParserForms$stack.elementAt(CUP$ParserForms$top-2)), ((java_cup.runtime.Symbol)CUP$ParserForms$stack.peek()), RESULT);
            }
          return CUP$ParserForms$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 18: // expresion_math ::= expresion_math_1 
            {
              Instruction RESULT =null;
		int aleft = ((java_cup.runtime.Symbol)CUP$ParserForms$stack.peek()).left;
		int aright = ((java_cup.runtime.Symbol)CUP$ParserForms$stack.peek()).right;
		Instruction a = (Instruction)((java_cup.runtime.Symbol) CUP$ParserForms$stack.peek()).value;
		 RESULT = a; 
              CUP$ParserForms$result = parser.getSymbolFactory().newSymbol("expresion_math",6, ((java_cup.runtime.Symbol)CUP$ParserForms$stack.peek()), ((java_cup.runtime.Symbol)CUP$ParserForms$stack.peek()), RESULT);
            }
          return CUP$ParserForms$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 19: // expresion_math_1 ::= expresion_math_1 MULTIPLICACION expresion_math_2 
            {
              Instruction RESULT =null;
		int aleft = ((java_cup.runtime.Symbol)CUP$ParserForms$stack.elementAt(CUP$ParserForms$top-2)).left;
		int aright = ((java_cup.runtime.Symbol)CUP$ParserForms$stack.elementAt(CUP$ParserForms$top-2)).right;
		Instruction a = (Instruction)((java_cup.runtime.Symbol) CUP$ParserForms$stack.elementAt(CUP$ParserForms$top-2)).value;
		int bleft = ((java_cup.runtime.Symbol)CUP$ParserForms$stack.peek()).left;
		int bright = ((java_cup.runtime.Symbol)CUP$ParserForms$stack.peek()).right;
		Instruction b = (Instruction)((java_cup.runtime.Symbol) CUP$ParserForms$stack.peek()).value;
		 RESULT = new Multiplicacion(a, b, aleft, aright); 
              CUP$ParserForms$result = parser.getSymbolFactory().newSymbol("expresion_math_1",7, ((java_cup.runtime.Symbol)CUP$ParserForms$stack.elementAt(CUP$ParserForms$top-2)), ((java_cup.runtime.Symbol)CUP$ParserForms$stack.peek()), RESULT);
            }
          return CUP$ParserForms$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 20: // expresion_math_1 ::= expresion_math_1 DIVISION expresion_math_2 
            {
              Instruction RESULT =null;
		int aleft = ((java_cup.runtime.Symbol)CUP$ParserForms$stack.elementAt(CUP$ParserForms$top-2)).left;
		int aright = ((java_cup.runtime.Symbol)CUP$ParserForms$stack.elementAt(CUP$ParserForms$top-2)).right;
		Instruction a = (Instruction)((java_cup.runtime.Symbol) CUP$ParserForms$stack.elementAt(CUP$ParserForms$top-2)).value;
		int bleft = ((java_cup.runtime.Symbol)CUP$ParserForms$stack.peek()).left;
		int bright = ((java_cup.runtime.Symbol)CUP$ParserForms$stack.peek()).right;
		Instruction b = (Instruction)((java_cup.runtime.Symbol) CUP$ParserForms$stack.peek()).value;
		 RESULT = new Division(a, b, aleft, aright); 
              CUP$ParserForms$result = parser.getSymbolFactory().newSymbol("expresion_math_1",7, ((java_cup.runtime.Symbol)CUP$ParserForms$stack.elementAt(CUP$ParserForms$top-2)), ((java_cup.runtime.Symbol)CUP$ParserForms$stack.peek()), RESULT);
            }
          return CUP$ParserForms$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 21: // expresion_math_1 ::= expresion_math_2 
            {
              Instruction RESULT =null;
		int aleft = ((java_cup.runtime.Symbol)CUP$ParserForms$stack.peek()).left;
		int aright = ((java_cup.runtime.Symbol)CUP$ParserForms$stack.peek()).right;
		Instruction a = (Instruction)((java_cup.runtime.Symbol) CUP$ParserForms$stack.peek()).value;
		 RESULT = a; 
              CUP$ParserForms$result = parser.getSymbolFactory().newSymbol("expresion_math_1",7, ((java_cup.runtime.Symbol)CUP$ParserForms$stack.peek()), ((java_cup.runtime.Symbol)CUP$ParserForms$stack.peek()), RESULT);
            }
          return CUP$ParserForms$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 22: // expresion_math_2 ::= expresion_math_2 POTENCIACION expresion_math_3 
            {
              Instruction RESULT =null;
		int aleft = ((java_cup.runtime.Symbol)CUP$ParserForms$stack.elementAt(CUP$ParserForms$top-2)).left;
		int aright = ((java_cup.runtime.Symbol)CUP$ParserForms$stack.elementAt(CUP$ParserForms$top-2)).right;
		Instruction a = (Instruction)((java_cup.runtime.Symbol) CUP$ParserForms$stack.elementAt(CUP$ParserForms$top-2)).value;
		int bleft = ((java_cup.runtime.Symbol)CUP$ParserForms$stack.peek()).left;
		int bright = ((java_cup.runtime.Symbol)CUP$ParserForms$stack.peek()).right;
		Instruction b = (Instruction)((java_cup.runtime.Symbol) CUP$ParserForms$stack.peek()).value;
		 RESULT = new Potenciacion(a, b, aleft, aright); 
              CUP$ParserForms$result = parser.getSymbolFactory().newSymbol("expresion_math_2",8, ((java_cup.runtime.Symbol)CUP$ParserForms$stack.elementAt(CUP$ParserForms$top-2)), ((java_cup.runtime.Symbol)CUP$ParserForms$stack.peek()), RESULT);
            }
          return CUP$ParserForms$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 23: // expresion_math_2 ::= expresion_math_2 MODULO expresion_math_3 
            {
              Instruction RESULT =null;
		int aleft = ((java_cup.runtime.Symbol)CUP$ParserForms$stack.elementAt(CUP$ParserForms$top-2)).left;
		int aright = ((java_cup.runtime.Symbol)CUP$ParserForms$stack.elementAt(CUP$ParserForms$top-2)).right;
		Instruction a = (Instruction)((java_cup.runtime.Symbol) CUP$ParserForms$stack.elementAt(CUP$ParserForms$top-2)).value;
		int bleft = ((java_cup.runtime.Symbol)CUP$ParserForms$stack.peek()).left;
		int bright = ((java_cup.runtime.Symbol)CUP$ParserForms$stack.peek()).right;
		Instruction b = (Instruction)((java_cup.runtime.Symbol) CUP$ParserForms$stack.peek()).value;
		 RESULT = new Modulo(a, b, aleft, aright); 
              CUP$ParserForms$result = parser.getSymbolFactory().newSymbol("expresion_math_2",8, ((java_cup.runtime.Symbol)CUP$ParserForms$stack.elementAt(CUP$ParserForms$top-2)), ((java_cup.runtime.Symbol)CUP$ParserForms$stack.peek()), RESULT);
            }
          return CUP$ParserForms$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 24: // expresion_math_2 ::= expresion_math_3 
            {
              Instruction RESULT =null;
		int aleft = ((java_cup.runtime.Symbol)CUP$ParserForms$stack.peek()).left;
		int aright = ((java_cup.runtime.Symbol)CUP$ParserForms$stack.peek()).right;
		Instruction a = (Instruction)((java_cup.runtime.Symbol) CUP$ParserForms$stack.peek()).value;
		 RESULT = a; 
              CUP$ParserForms$result = parser.getSymbolFactory().newSymbol("expresion_math_2",8, ((java_cup.runtime.Symbol)CUP$ParserForms$stack.peek()), ((java_cup.runtime.Symbol)CUP$ParserForms$stack.peek()), RESULT);
            }
          return CUP$ParserForms$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 25: // expresion_math_3 ::= LPAREN expresion_math RPAREN 
            {
              Instruction RESULT =null;
		int aleft = ((java_cup.runtime.Symbol)CUP$ParserForms$stack.elementAt(CUP$ParserForms$top-1)).left;
		int aright = ((java_cup.runtime.Symbol)CUP$ParserForms$stack.elementAt(CUP$ParserForms$top-1)).right;
		Instruction a = (Instruction)((java_cup.runtime.Symbol) CUP$ParserForms$stack.elementAt(CUP$ParserForms$top-1)).value;
		 RESULT = a; 
              CUP$ParserForms$result = parser.getSymbolFactory().newSymbol("expresion_math_3",9, ((java_cup.runtime.Symbol)CUP$ParserForms$stack.elementAt(CUP$ParserForms$top-2)), ((java_cup.runtime.Symbol)CUP$ParserForms$stack.peek()), RESULT);
            }
          return CUP$ParserForms$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 26: // expresion_math_3 ::= valores_variables 
            {
              Instruction RESULT =null;
		int aleft = ((java_cup.runtime.Symbol)CUP$ParserForms$stack.peek()).left;
		int aright = ((java_cup.runtime.Symbol)CUP$ParserForms$stack.peek()).right;
		Instruction a = (Instruction)((java_cup.runtime.Symbol) CUP$ParserForms$stack.peek()).value;
		 RESULT = a; 
              CUP$ParserForms$result = parser.getSymbolFactory().newSymbol("expresion_math_3",9, ((java_cup.runtime.Symbol)CUP$ParserForms$stack.peek()), ((java_cup.runtime.Symbol)CUP$ParserForms$stack.peek()), RESULT);
            }
          return CUP$ParserForms$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 27: // guardado_texto ::= TEXTO 
            {
              Instruction RESULT =null;
		int aleft = ((java_cup.runtime.Symbol)CUP$ParserForms$stack.peek()).left;
		int aright = ((java_cup.runtime.Symbol)CUP$ParserForms$stack.peek()).right;
		Object a = (Object)((java_cup.runtime.Symbol) CUP$ParserForms$stack.peek()).value;
		 RESULT = new Native(a, new Type(TypeData.STRING), aleft, aright); 
              CUP$ParserForms$result = parser.getSymbolFactory().newSymbol("guardado_texto",11, ((java_cup.runtime.Symbol)CUP$ParserForms$stack.peek()), ((java_cup.runtime.Symbol)CUP$ParserForms$stack.peek()), RESULT);
            }
          return CUP$ParserForms$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 28: // valores_variables ::= IDENTIFICADOR 
            {
              Instruction RESULT =null;
		int aleft = ((java_cup.runtime.Symbol)CUP$ParserForms$stack.peek()).left;
		int aright = ((java_cup.runtime.Symbol)CUP$ParserForms$stack.peek()).right;
		Object a = (Object)((java_cup.runtime.Symbol) CUP$ParserForms$stack.peek()).value;
		RESULT = new AccesVariable((String) a, aleft, aright);
              CUP$ParserForms$result = parser.getSymbolFactory().newSymbol("valores_variables",10, ((java_cup.runtime.Symbol)CUP$ParserForms$stack.peek()), ((java_cup.runtime.Symbol)CUP$ParserForms$stack.peek()), RESULT);
            }
          return CUP$ParserForms$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 29: // valores_variables ::= DECIMAL 
            {
              Instruction RESULT =null;
		int aleft = ((java_cup.runtime.Symbol)CUP$ParserForms$stack.peek()).left;
		int aright = ((java_cup.runtime.Symbol)CUP$ParserForms$stack.peek()).right;
		Object a = (Object)((java_cup.runtime.Symbol) CUP$ParserForms$stack.peek()).value;
		 RESULT = new Native(Double.parseDouble(a.toString()), new Type(TypeData.DECIMAL), aleft, aright); 
              CUP$ParserForms$result = parser.getSymbolFactory().newSymbol("valores_variables",10, ((java_cup.runtime.Symbol)CUP$ParserForms$stack.peek()), ((java_cup.runtime.Symbol)CUP$ParserForms$stack.peek()), RESULT);
            }
          return CUP$ParserForms$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 30: // valores_variables ::= ENTEROS 
            {
              Instruction RESULT =null;
		int aleft = ((java_cup.runtime.Symbol)CUP$ParserForms$stack.peek()).left;
		int aright = ((java_cup.runtime.Symbol)CUP$ParserForms$stack.peek()).right;
		Object a = (Object)((java_cup.runtime.Symbol) CUP$ParserForms$stack.peek()).value;
		 RESULT = new Native(Integer.parseInt(a.toString()), new Type(TypeData.INTEGER), aleft, aright); 
              CUP$ParserForms$result = parser.getSymbolFactory().newSymbol("valores_variables",10, ((java_cup.runtime.Symbol)CUP$ParserForms$stack.peek()), ((java_cup.runtime.Symbol)CUP$ParserForms$stack.peek()), RESULT);
            }
          return CUP$ParserForms$result;

          /* . . . . . .*/
          default:
            throw new Exception(
               "Invalid action number "+CUP$ParserForms$act_num+"found in internal parse table");

        }
    } /* end of method */

  /** Method splitting the generated action code into several parts. */
  public final java_cup.runtime.Symbol CUP$ParserForms$do_action(
    int                        CUP$ParserForms$act_num,
    java_cup.runtime.lr_parser CUP$ParserForms$parser,
    java.util.Stack            CUP$ParserForms$stack,
    int                        CUP$ParserForms$top)
    throws java.lang.Exception
    {
              return CUP$ParserForms$do_action_part00000000(
                               CUP$ParserForms$act_num,
                               CUP$ParserForms$parser,
                               CUP$ParserForms$stack,
                               CUP$ParserForms$top);
    }
}

}
