
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

package com.example.pkm_forms.Analizadores.Forms;

import java_cup.runtime.Symbol;
import com.example.pkm_forms.Models.*;
import com.example.pkm_forms.Patron.Instruction;
import com.example.pkm_forms.Expression.Aritmeticos.Division;
import com.example.pkm_forms.Expression.Aritmeticos.Multiplicacion;
import com.example.pkm_forms.Expression.Aritmeticos.Modulo;
import com.example.pkm_forms.Expression.Aritmeticos.Potenciacion;
import com.example.pkm_forms.Expression.Aritmeticos.Resta;
import com.example.pkm_forms.Expression.Aritmeticos.Suma;
import com.example.pkm_forms.Expression.Aritmeticos.NegacionAritmetica;
import com.example.pkm_forms.Expression.Native;
import com.example.pkm_forms.Instruction.Variable.*;
import com.example.pkm_forms.Instruction.Print;
import java.util.List;
import java.util.ArrayList;
import java.util.LinkedList;
import java_cup.runtime.XMLElement;

/** CUP v0.11b 20160615 (GIT 4ac7450) generated parser.
  */
@SuppressWarnings({"rawtypes"})
public class ParserForms extends java_cup.runtime.lr_parser {

 public final Class getSymbolContainer() {
    return sym.class;
}

  /** Default constructor. */
  @Deprecated
  public ParserForms() {super();}

  /** Constructor which sets the default scanner. */
  @Deprecated
  public ParserForms(java_cup.runtime.Scanner s) {super(s);}

  /** Constructor which sets the default scanner. */
  public ParserForms(java_cup.runtime.Scanner s, java_cup.runtime.SymbolFactory sf) {super(s,sf);}

  /** Production table. */
  protected static final short _production_table[][] = 
    unpackFromStrings(new String[] {
    "\000\027\000\002\002\004\000\002\002\003\000\002\003" +
    "\004\000\002\003\003\000\002\004\003\000\002\004\003" +
    "\000\002\007\006\000\002\005\004\000\002\010\004\000" +
    "\002\010\005\000\002\010\005\000\002\010\003\000\002" +
    "\011\005\000\002\011\005\000\002\011\003\000\002\012" +
    "\005\000\002\012\005\000\002\012\003\000\002\013\005" +
    "\000\002\013\003\000\002\014\003\000\002\014\003\000" +
    "\002\014\003" });

  /** Access to production table. */
  public short[][] production_table() {return _production_table;}

  /** Parse-action table. */
  protected static final short[][] _action_table = 
    unpackFromStrings(new String[] {
    "\000\046\000\006\004\011\064\010\001\002\000\004\002" +
    "\050\001\002\000\010\002\ufffe\004\ufffe\064\ufffe\001\002" +
    "\000\010\002\000\004\011\064\010\001\002\000\010\002" +
    "\ufffd\004\ufffd\064\ufffd\001\002\000\014\071\024\076\025" +
    "\123\023\124\015\125\026\001\002\000\004\125\013\001" +
    "\002\000\010\002\ufffc\004\ufffc\064\ufffc\001\002\000\004" +
    "\113\014\001\002\000\014\071\024\076\025\123\023\124" +
    "\015\125\026\001\002\000\026\002\uffec\004\uffec\064\uffec" +
    "\070\uffec\071\uffec\072\uffec\073\uffec\074\uffec\075\uffec\077" +
    "\uffec\001\002\000\014\002\ufffb\004\ufffb\064\ufffb\070\032" +
    "\071\030\001\002\000\026\002\uffee\004\uffee\064\uffee\070" +
    "\uffee\071\uffee\072\uffee\073\uffee\074\uffee\075\uffee\077\uffee" +
    "\001\002\000\026\002\ufff0\004\ufff0\064\ufff0\070\ufff0\071" +
    "\ufff0\072\ufff0\073\ufff0\074\ufff0\075\ufff0\077\ufff0\001\002" +
    "\000\026\002\ufff3\004\ufff3\064\ufff3\070\ufff3\071\ufff3\072" +
    "\ufff3\073\ufff3\074\040\075\037\077\ufff3\001\002\000\022" +
    "\002\ufff6\004\ufff6\064\ufff6\070\ufff6\071\ufff6\072\035\073" +
    "\034\077\ufff6\001\002\000\026\002\uffeb\004\uffeb\064\uffeb" +
    "\070\uffeb\071\uffeb\072\uffeb\073\uffeb\074\uffeb\075\uffeb\077" +
    "\uffeb\001\002\000\014\071\024\076\025\123\023\124\015" +
    "\125\026\001\002\000\014\071\024\076\025\123\023\124" +
    "\015\125\026\001\002\000\026\002\uffed\004\uffed\064\uffed" +
    "\070\uffed\071\uffed\072\uffed\073\uffed\074\uffed\075\uffed\077" +
    "\uffed\001\002\000\010\070\032\071\030\077\031\001\002" +
    "\000\012\076\025\123\023\124\015\125\026\001\002\000" +
    "\026\002\uffef\004\uffef\064\uffef\070\uffef\071\uffef\072\uffef" +
    "\073\uffef\074\uffef\075\uffef\077\uffef\001\002\000\012\076" +
    "\025\123\023\124\015\125\026\001\002\000\022\002\ufff8" +
    "\004\ufff8\064\ufff8\070\ufff8\071\ufff8\072\035\073\034\077" +
    "\ufff8\001\002\000\012\076\025\123\023\124\015\125\026" +
    "\001\002\000\012\076\025\123\023\124\015\125\026\001" +
    "\002\000\026\002\ufff4\004\ufff4\064\ufff4\070\ufff4\071\ufff4" +
    "\072\ufff4\073\ufff4\074\040\075\037\077\ufff4\001\002\000" +
    "\012\076\025\123\023\124\015\125\026\001\002\000\012" +
    "\076\025\123\023\124\015\125\026\001\002\000\026\002" +
    "\ufff2\004\ufff2\064\ufff2\070\ufff2\071\ufff2\072\ufff2\073\ufff2" +
    "\074\ufff2\075\ufff2\077\ufff2\001\002\000\026\002\ufff1\004" +
    "\ufff1\064\ufff1\070\ufff1\071\ufff1\072\ufff1\073\ufff1\074\ufff1" +
    "\075\ufff1\077\ufff1\001\002\000\026\002\ufff5\004\ufff5\064" +
    "\ufff5\070\ufff5\071\ufff5\072\ufff5\073\ufff5\074\040\075\037" +
    "\077\ufff5\001\002\000\022\002\ufff7\004\ufff7\064\ufff7\070" +
    "\ufff7\071\ufff7\072\035\073\034\077\ufff7\001\002\000\016" +
    "\002\ufff9\004\ufff9\064\ufff9\070\ufff9\071\ufff9\077\ufff9\001" +
    "\002\000\014\002\ufffa\004\ufffa\064\ufffa\070\032\071\030" +
    "\001\002\000\010\002\uffff\004\uffff\064\uffff\001\002\000" +
    "\004\002\001\001\002" });

  /** Access to parse-action table. */
  public short[][] action_table() {return _action_table;}

  /** <code>reduce_goto</code> table. */
  protected static final short[][] _reduce_table = 
    unpackFromStrings(new String[] {
    "\000\046\000\014\002\003\003\005\004\004\005\006\007" +
    "\011\001\001\000\002\001\001\000\002\001\001\000\010" +
    "\004\046\005\006\007\011\001\001\000\002\001\001\000" +
    "\014\010\045\011\021\012\020\013\017\014\016\001\001" +
    "\000\002\001\001\000\002\001\001\000\002\001\001\000" +
    "\014\010\015\011\021\012\020\013\017\014\016\001\001" +
    "\000\002\001\001\000\002\001\001\000\002\001\001\000" +
    "\002\001\001\000\002\001\001\000\002\001\001\000\002" +
    "\001\001\000\014\010\044\011\021\012\020\013\017\014" +
    "\016\001\001\000\014\010\026\011\021\012\020\013\017" +
    "\014\016\001\001\000\002\001\001\000\002\001\001\000" +
    "\012\011\043\012\020\013\017\014\016\001\001\000\002" +
    "\001\001\000\012\011\032\012\020\013\017\014\016\001" +
    "\001\000\002\001\001\000\010\012\042\013\017\014\016" +
    "\001\001\000\010\012\035\013\017\014\016\001\001\000" +
    "\002\001\001\000\006\013\041\014\016\001\001\000\006" +
    "\013\040\014\016\001\001\000\002\001\001\000\002\001" +
    "\001\000\002\001\001\000\002\001\001\000\002\001\001" +
    "\000\002\001\001\000\002\001\001\000\002\001\001" });

  /** Access to <code>reduce_goto</code> table. */
  public short[][] reduce_table() {return _reduce_table;}

  /** Instance of action encapsulation class. */
  protected CUP$ParserForms$actions action_obj;

  /** Action encapsulation object initializer. */
  protected void init_actions()
    {
      action_obj = new CUP$ParserForms$actions(this);
    }

  /** Invoke a user supplied parse action. */
  public java_cup.runtime.Symbol do_action(
    int                        act_num,
    java_cup.runtime.lr_parser parser,
    java.util.Stack            stack,
    int                        top)
    throws java.lang.Exception
  {
    /* call code in generated class */
    return action_obj.CUP$ParserForms$do_action(act_num, parser, stack, top);
  }

  /** Indicates start state. */
  public int start_state() {return 0;}
  /** Indicates start production. */
  public int start_production() {return 0;}

  /** <code>EOF</code> Symbol index. */
  public int EOF_sym() {return 0;}

  /** <code>error</code> Symbol index. */
  public int error_sym() {return 1;}



/*
    //Listas para guardar Errores sintacticos
    Parser s;
    Parser(Parser s){this.s = s;}

    public LinkedList<SintaxError> listErrorSintactico = new LinkedList<>();

    public void syntax_error(Symbol s){
        listErrorSintactico.add(new SintaxError("Error de sintaxis recuperable", "No se esperaba: " +s.value, s.left, s.right));
    }

    public void unrecovered_syntax_(Symbol s) throws java.lang.Exception{
        listErrorSintactico.add(new SintaxError("Error de sintaxis no recuperable", "No se esperaba: " +s.value, s.left, s.right));
    }*/


/** Cup generated class to encapsulate user supplied action code.*/
@SuppressWarnings({"rawtypes", "unchecked", "unused"})
class CUP$ParserForms$actions {



    String console = "";


  private final ParserForms parser;

  /** Constructor */
  CUP$ParserForms$actions(ParserForms parser) {
    this.parser = parser;
  }

  /** Method 0 with the actual generated action code for actions 0 to 300. */
  public final java_cup.runtime.Symbol CUP$ParserForms$do_action_part00000000(
    int                        CUP$ParserForms$act_num,
    java_cup.runtime.lr_parser CUP$ParserForms$parser,
    java.util.Stack            CUP$ParserForms$stack,
    int                        CUP$ParserForms$top)
    throws java.lang.Exception
    {
      /* Symbol object for return from actions */
      java_cup.runtime.Symbol CUP$ParserForms$result;

      /* select the action based on the action number */
      switch (CUP$ParserForms$act_num)
        {
          /*. . . . . . . . . . . . . . . . . . . .*/
          case 0: // $START ::= initiation EOF 
            {
              Object RESULT =null;
		int start_valleft = ((java_cup.runtime.Symbol)CUP$ParserForms$stack.elementAt(CUP$ParserForms$top-1)).left;
		int start_valright = ((java_cup.runtime.Symbol)CUP$ParserForms$stack.elementAt(CUP$ParserForms$top-1)).right;
		LinkedList<Instruction> start_val = (LinkedList<Instruction>)((java_cup.runtime.Symbol) CUP$ParserForms$stack.elementAt(CUP$ParserForms$top-1)).value;
		RESULT = start_val;
              CUP$ParserForms$result = parser.getSymbolFactory().newSymbol("$START",0, ((java_cup.runtime.Symbol)CUP$ParserForms$stack.elementAt(CUP$ParserForms$top-1)), ((java_cup.runtime.Symbol)CUP$ParserForms$stack.peek()), RESULT);
            }
          /* ACCEPT */
          CUP$ParserForms$parser.done_parsing();
          return CUP$ParserForms$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 1: // initiation ::= instructions 
            {
              LinkedList<Instruction> RESULT =null;
		int aleft = ((java_cup.runtime.Symbol)CUP$ParserForms$stack.peek()).left;
		int aright = ((java_cup.runtime.Symbol)CUP$ParserForms$stack.peek()).right;
		LinkedList<Instruction> a = (LinkedList<Instruction>)((java_cup.runtime.Symbol) CUP$ParserForms$stack.peek()).value;
		 RESULT = a; 
              CUP$ParserForms$result = parser.getSymbolFactory().newSymbol("initiation",0, ((java_cup.runtime.Symbol)CUP$ParserForms$stack.peek()), ((java_cup.runtime.Symbol)CUP$ParserForms$stack.peek()), RESULT);
            }
          return CUP$ParserForms$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 2: // instructions ::= instructions instruction 
            {
              LinkedList<Instruction> RESULT =null;
		int aleft = ((java_cup.runtime.Symbol)CUP$ParserForms$stack.elementAt(CUP$ParserForms$top-1)).left;
		int aright = ((java_cup.runtime.Symbol)CUP$ParserForms$stack.elementAt(CUP$ParserForms$top-1)).right;
		LinkedList<Instruction> a = (LinkedList<Instruction>)((java_cup.runtime.Symbol) CUP$ParserForms$stack.elementAt(CUP$ParserForms$top-1)).value;
		int bleft = ((java_cup.runtime.Symbol)CUP$ParserForms$stack.peek()).left;
		int bright = ((java_cup.runtime.Symbol)CUP$ParserForms$stack.peek()).right;
		Instruction b = (Instruction)((java_cup.runtime.Symbol) CUP$ParserForms$stack.peek()).value;
		 RESULT = a; RESULT.add(b); 
              CUP$ParserForms$result = parser.getSymbolFactory().newSymbol("instructions",1, ((java_cup.runtime.Symbol)CUP$ParserForms$stack.elementAt(CUP$ParserForms$top-1)), ((java_cup.runtime.Symbol)CUP$ParserForms$stack.peek()), RESULT);
            }
          return CUP$ParserForms$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 3: // instructions ::= instruction 
            {
              LinkedList<Instruction> RESULT =null;
		int aleft = ((java_cup.runtime.Symbol)CUP$ParserForms$stack.peek()).left;
		int aright = ((java_cup.runtime.Symbol)CUP$ParserForms$stack.peek()).right;
		Instruction a = (Instruction)((java_cup.runtime.Symbol) CUP$ParserForms$stack.peek()).value;
		 RESULT = new LinkedList<Instruction>(); RESULT.add(a); 
              CUP$ParserForms$result = parser.getSymbolFactory().newSymbol("instructions",1, ((java_cup.runtime.Symbol)CUP$ParserForms$stack.peek()), ((java_cup.runtime.Symbol)CUP$ParserForms$stack.peek()), RESULT);
            }
          return CUP$ParserForms$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 4: // instruction ::= print 
            {
              Instruction RESULT =null;
		int aleft = ((java_cup.runtime.Symbol)CUP$ParserForms$stack.peek()).left;
		int aright = ((java_cup.runtime.Symbol)CUP$ParserForms$stack.peek()).right;
		Instruction a = (Instruction)((java_cup.runtime.Symbol) CUP$ParserForms$stack.peek()).value;
		 RESULT = a; 
              CUP$ParserForms$result = parser.getSymbolFactory().newSymbol("instruction",2, ((java_cup.runtime.Symbol)CUP$ParserForms$stack.peek()), ((java_cup.runtime.Symbol)CUP$ParserForms$stack.peek()), RESULT);
            }
          return CUP$ParserForms$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 5: // instruction ::= declaration 
            {
              Instruction RESULT =null;
		int aleft = ((java_cup.runtime.Symbol)CUP$ParserForms$stack.peek()).left;
		int aright = ((java_cup.runtime.Symbol)CUP$ParserForms$stack.peek()).right;
		Instruction a = (Instruction)((java_cup.runtime.Symbol) CUP$ParserForms$stack.peek()).value;
		 RESULT = a; 
              CUP$ParserForms$result = parser.getSymbolFactory().newSymbol("instruction",2, ((java_cup.runtime.Symbol)CUP$ParserForms$stack.peek()), ((java_cup.runtime.Symbol)CUP$ParserForms$stack.peek()), RESULT);
            }
          return CUP$ParserForms$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 6: // declaration ::= NUMBER IDENTIFICADOR IGUAL expresion_math 
            {
              Instruction RESULT =null;
		int aleft = ((java_cup.runtime.Symbol)CUP$ParserForms$stack.elementAt(CUP$ParserForms$top-2)).left;
		int aright = ((java_cup.runtime.Symbol)CUP$ParserForms$stack.elementAt(CUP$ParserForms$top-2)).right;
		Object a = (Object)((java_cup.runtime.Symbol) CUP$ParserForms$stack.elementAt(CUP$ParserForms$top-2)).value;
		int bleft = ((java_cup.runtime.Symbol)CUP$ParserForms$stack.peek()).left;
		int bright = ((java_cup.runtime.Symbol)CUP$ParserForms$stack.peek()).right;
		Instruction b = (Instruction)((java_cup.runtime.Symbol) CUP$ParserForms$stack.peek()).value;
		 RESULT = new Declaration((String) a, b, aleft, aright); 
              CUP$ParserForms$result = parser.getSymbolFactory().newSymbol("declaration",5, ((java_cup.runtime.Symbol)CUP$ParserForms$stack.elementAt(CUP$ParserForms$top-3)), ((java_cup.runtime.Symbol)CUP$ParserForms$stack.peek()), RESULT);
            }
          return CUP$ParserForms$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 7: // print ::= FOR expresion_math 
            {
              Instruction RESULT =null;
		int aleft = ((java_cup.runtime.Symbol)CUP$ParserForms$stack.peek()).left;
		int aright = ((java_cup.runtime.Symbol)CUP$ParserForms$stack.peek()).right;
		Instruction a = (Instruction)((java_cup.runtime.Symbol) CUP$ParserForms$stack.peek()).value;
		 RESULT = new Print(a, aleft, aright); 
              CUP$ParserForms$result = parser.getSymbolFactory().newSymbol("print",3, ((java_cup.runtime.Symbol)CUP$ParserForms$stack.elementAt(CUP$ParserForms$top-1)), ((java_cup.runtime.Symbol)CUP$ParserForms$stack.peek()), RESULT);
            }
          return CUP$ParserForms$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 8: // expresion_math ::= RESTA expresion_math 
            {
              Instruction RESULT =null;
		int aleft = ((java_cup.runtime.Symbol)CUP$ParserForms$stack.peek()).left;
		int aright = ((java_cup.runtime.Symbol)CUP$ParserForms$stack.peek()).right;
		Instruction a = (Instruction)((java_cup.runtime.Symbol) CUP$ParserForms$stack.peek()).value;
		 RESULT  = new NegacionAritmetica(a, aleft, aright); 
              CUP$ParserForms$result = parser.getSymbolFactory().newSymbol("expresion_math",6, ((java_cup.runtime.Symbol)CUP$ParserForms$stack.elementAt(CUP$ParserForms$top-1)), ((java_cup.runtime.Symbol)CUP$ParserForms$stack.peek()), RESULT);
            }
          return CUP$ParserForms$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 9: // expresion_math ::= expresion_math SUMA expresion_math_1 
            {
              Instruction RESULT =null;
		int aleft = ((java_cup.runtime.Symbol)CUP$ParserForms$stack.elementAt(CUP$ParserForms$top-2)).left;
		int aright = ((java_cup.runtime.Symbol)CUP$ParserForms$stack.elementAt(CUP$ParserForms$top-2)).right;
		Instruction a = (Instruction)((java_cup.runtime.Symbol) CUP$ParserForms$stack.elementAt(CUP$ParserForms$top-2)).value;
		int bleft = ((java_cup.runtime.Symbol)CUP$ParserForms$stack.peek()).left;
		int bright = ((java_cup.runtime.Symbol)CUP$ParserForms$stack.peek()).right;
		Instruction b = (Instruction)((java_cup.runtime.Symbol) CUP$ParserForms$stack.peek()).value;
		 RESULT  = new Suma(a, b, aleft, aright); 
              CUP$ParserForms$result = parser.getSymbolFactory().newSymbol("expresion_math",6, ((java_cup.runtime.Symbol)CUP$ParserForms$stack.elementAt(CUP$ParserForms$top-2)), ((java_cup.runtime.Symbol)CUP$ParserForms$stack.peek()), RESULT);
            }
          return CUP$ParserForms$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 10: // expresion_math ::= expresion_math RESTA expresion_math_1 
            {
              Instruction RESULT =null;
		int aleft = ((java_cup.runtime.Symbol)CUP$ParserForms$stack.elementAt(CUP$ParserForms$top-2)).left;
		int aright = ((java_cup.runtime.Symbol)CUP$ParserForms$stack.elementAt(CUP$ParserForms$top-2)).right;
		Instruction a = (Instruction)((java_cup.runtime.Symbol) CUP$ParserForms$stack.elementAt(CUP$ParserForms$top-2)).value;
		int bleft = ((java_cup.runtime.Symbol)CUP$ParserForms$stack.peek()).left;
		int bright = ((java_cup.runtime.Symbol)CUP$ParserForms$stack.peek()).right;
		Instruction b = (Instruction)((java_cup.runtime.Symbol) CUP$ParserForms$stack.peek()).value;
		 RESULT = new Resta(a, b, aleft, aright); 
              CUP$ParserForms$result = parser.getSymbolFactory().newSymbol("expresion_math",6, ((java_cup.runtime.Symbol)CUP$ParserForms$stack.elementAt(CUP$ParserForms$top-2)), ((java_cup.runtime.Symbol)CUP$ParserForms$stack.peek()), RESULT);
            }
          return CUP$ParserForms$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 11: // expresion_math ::= expresion_math_1 
            {
              Instruction RESULT =null;
		int aleft = ((java_cup.runtime.Symbol)CUP$ParserForms$stack.peek()).left;
		int aright = ((java_cup.runtime.Symbol)CUP$ParserForms$stack.peek()).right;
		Instruction a = (Instruction)((java_cup.runtime.Symbol) CUP$ParserForms$stack.peek()).value;
		 RESULT = a; 
              CUP$ParserForms$result = parser.getSymbolFactory().newSymbol("expresion_math",6, ((java_cup.runtime.Symbol)CUP$ParserForms$stack.peek()), ((java_cup.runtime.Symbol)CUP$ParserForms$stack.peek()), RESULT);
            }
          return CUP$ParserForms$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 12: // expresion_math_1 ::= expresion_math_1 MULTIPLICACION expresion_math_2 
            {
              Instruction RESULT =null;
		int aleft = ((java_cup.runtime.Symbol)CUP$ParserForms$stack.elementAt(CUP$ParserForms$top-2)).left;
		int aright = ((java_cup.runtime.Symbol)CUP$ParserForms$stack.elementAt(CUP$ParserForms$top-2)).right;
		Instruction a = (Instruction)((java_cup.runtime.Symbol) CUP$ParserForms$stack.elementAt(CUP$ParserForms$top-2)).value;
		int bleft = ((java_cup.runtime.Symbol)CUP$ParserForms$stack.peek()).left;
		int bright = ((java_cup.runtime.Symbol)CUP$ParserForms$stack.peek()).right;
		Instruction b = (Instruction)((java_cup.runtime.Symbol) CUP$ParserForms$stack.peek()).value;
		 RESULT = new Multiplicacion(a, b, aleft, aright); 
              CUP$ParserForms$result = parser.getSymbolFactory().newSymbol("expresion_math_1",7, ((java_cup.runtime.Symbol)CUP$ParserForms$stack.elementAt(CUP$ParserForms$top-2)), ((java_cup.runtime.Symbol)CUP$ParserForms$stack.peek()), RESULT);
            }
          return CUP$ParserForms$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 13: // expresion_math_1 ::= expresion_math_1 DIVISION expresion_math_2 
            {
              Instruction RESULT =null;
		int aleft = ((java_cup.runtime.Symbol)CUP$ParserForms$stack.elementAt(CUP$ParserForms$top-2)).left;
		int aright = ((java_cup.runtime.Symbol)CUP$ParserForms$stack.elementAt(CUP$ParserForms$top-2)).right;
		Instruction a = (Instruction)((java_cup.runtime.Symbol) CUP$ParserForms$stack.elementAt(CUP$ParserForms$top-2)).value;
		int bleft = ((java_cup.runtime.Symbol)CUP$ParserForms$stack.peek()).left;
		int bright = ((java_cup.runtime.Symbol)CUP$ParserForms$stack.peek()).right;
		Instruction b = (Instruction)((java_cup.runtime.Symbol) CUP$ParserForms$stack.peek()).value;
		 RESULT = new Division(a, b, aleft, aright); 
              CUP$ParserForms$result = parser.getSymbolFactory().newSymbol("expresion_math_1",7, ((java_cup.runtime.Symbol)CUP$ParserForms$stack.elementAt(CUP$ParserForms$top-2)), ((java_cup.runtime.Symbol)CUP$ParserForms$stack.peek()), RESULT);
            }
          return CUP$ParserForms$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 14: // expresion_math_1 ::= expresion_math_2 
            {
              Instruction RESULT =null;
		int aleft = ((java_cup.runtime.Symbol)CUP$ParserForms$stack.peek()).left;
		int aright = ((java_cup.runtime.Symbol)CUP$ParserForms$stack.peek()).right;
		Instruction a = (Instruction)((java_cup.runtime.Symbol) CUP$ParserForms$stack.peek()).value;
		 RESULT = a; 
              CUP$ParserForms$result = parser.getSymbolFactory().newSymbol("expresion_math_1",7, ((java_cup.runtime.Symbol)CUP$ParserForms$stack.peek()), ((java_cup.runtime.Symbol)CUP$ParserForms$stack.peek()), RESULT);
            }
          return CUP$ParserForms$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 15: // expresion_math_2 ::= expresion_math_2 POTENCIACION expresion_math_3 
            {
              Instruction RESULT =null;
		int aleft = ((java_cup.runtime.Symbol)CUP$ParserForms$stack.elementAt(CUP$ParserForms$top-2)).left;
		int aright = ((java_cup.runtime.Symbol)CUP$ParserForms$stack.elementAt(CUP$ParserForms$top-2)).right;
		Instruction a = (Instruction)((java_cup.runtime.Symbol) CUP$ParserForms$stack.elementAt(CUP$ParserForms$top-2)).value;
		int bleft = ((java_cup.runtime.Symbol)CUP$ParserForms$stack.peek()).left;
		int bright = ((java_cup.runtime.Symbol)CUP$ParserForms$stack.peek()).right;
		Instruction b = (Instruction)((java_cup.runtime.Symbol) CUP$ParserForms$stack.peek()).value;
		 RESULT = new Potenciacion(a, b, aleft, aright); 
              CUP$ParserForms$result = parser.getSymbolFactory().newSymbol("expresion_math_2",8, ((java_cup.runtime.Symbol)CUP$ParserForms$stack.elementAt(CUP$ParserForms$top-2)), ((java_cup.runtime.Symbol)CUP$ParserForms$stack.peek()), RESULT);
            }
          return CUP$ParserForms$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 16: // expresion_math_2 ::= expresion_math_2 MODULO expresion_math_3 
            {
              Instruction RESULT =null;
		int aleft = ((java_cup.runtime.Symbol)CUP$ParserForms$stack.elementAt(CUP$ParserForms$top-2)).left;
		int aright = ((java_cup.runtime.Symbol)CUP$ParserForms$stack.elementAt(CUP$ParserForms$top-2)).right;
		Instruction a = (Instruction)((java_cup.runtime.Symbol) CUP$ParserForms$stack.elementAt(CUP$ParserForms$top-2)).value;
		int bleft = ((java_cup.runtime.Symbol)CUP$ParserForms$stack.peek()).left;
		int bright = ((java_cup.runtime.Symbol)CUP$ParserForms$stack.peek()).right;
		Instruction b = (Instruction)((java_cup.runtime.Symbol) CUP$ParserForms$stack.peek()).value;
		 RESULT = new Modulo(a, b, aleft, aright); 
              CUP$ParserForms$result = parser.getSymbolFactory().newSymbol("expresion_math_2",8, ((java_cup.runtime.Symbol)CUP$ParserForms$stack.elementAt(CUP$ParserForms$top-2)), ((java_cup.runtime.Symbol)CUP$ParserForms$stack.peek()), RESULT);
            }
          return CUP$ParserForms$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 17: // expresion_math_2 ::= expresion_math_3 
            {
              Instruction RESULT =null;
		int aleft = ((java_cup.runtime.Symbol)CUP$ParserForms$stack.peek()).left;
		int aright = ((java_cup.runtime.Symbol)CUP$ParserForms$stack.peek()).right;
		Instruction a = (Instruction)((java_cup.runtime.Symbol) CUP$ParserForms$stack.peek()).value;
		 RESULT = a; 
              CUP$ParserForms$result = parser.getSymbolFactory().newSymbol("expresion_math_2",8, ((java_cup.runtime.Symbol)CUP$ParserForms$stack.peek()), ((java_cup.runtime.Symbol)CUP$ParserForms$stack.peek()), RESULT);
            }
          return CUP$ParserForms$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 18: // expresion_math_3 ::= LPAREN expresion_math RPAREN 
            {
              Instruction RESULT =null;
		int aleft = ((java_cup.runtime.Symbol)CUP$ParserForms$stack.elementAt(CUP$ParserForms$top-1)).left;
		int aright = ((java_cup.runtime.Symbol)CUP$ParserForms$stack.elementAt(CUP$ParserForms$top-1)).right;
		Instruction a = (Instruction)((java_cup.runtime.Symbol) CUP$ParserForms$stack.elementAt(CUP$ParserForms$top-1)).value;
		 RESULT = a; 
              CUP$ParserForms$result = parser.getSymbolFactory().newSymbol("expresion_math_3",9, ((java_cup.runtime.Symbol)CUP$ParserForms$stack.elementAt(CUP$ParserForms$top-2)), ((java_cup.runtime.Symbol)CUP$ParserForms$stack.peek()), RESULT);
            }
          return CUP$ParserForms$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 19: // expresion_math_3 ::= valores_variables 
            {
              Instruction RESULT =null;
		int aleft = ((java_cup.runtime.Symbol)CUP$ParserForms$stack.peek()).left;
		int aright = ((java_cup.runtime.Symbol)CUP$ParserForms$stack.peek()).right;
		Instruction a = (Instruction)((java_cup.runtime.Symbol) CUP$ParserForms$stack.peek()).value;
		 RESULT = a; 
              CUP$ParserForms$result = parser.getSymbolFactory().newSymbol("expresion_math_3",9, ((java_cup.runtime.Symbol)CUP$ParserForms$stack.peek()), ((java_cup.runtime.Symbol)CUP$ParserForms$stack.peek()), RESULT);
            }
          return CUP$ParserForms$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 20: // valores_variables ::= IDENTIFICADOR 
            {
              Instruction RESULT =null;
		int aleft = ((java_cup.runtime.Symbol)CUP$ParserForms$stack.peek()).left;
		int aright = ((java_cup.runtime.Symbol)CUP$ParserForms$stack.peek()).right;
		Object a = (Object)((java_cup.runtime.Symbol) CUP$ParserForms$stack.peek()).value;
		RESULT = new AccesVariable((String) a, aleft, aright);
              CUP$ParserForms$result = parser.getSymbolFactory().newSymbol("valores_variables",10, ((java_cup.runtime.Symbol)CUP$ParserForms$stack.peek()), ((java_cup.runtime.Symbol)CUP$ParserForms$stack.peek()), RESULT);
            }
          return CUP$ParserForms$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 21: // valores_variables ::= DECIMAL 
            {
              Instruction RESULT =null;
		int aleft = ((java_cup.runtime.Symbol)CUP$ParserForms$stack.peek()).left;
		int aright = ((java_cup.runtime.Symbol)CUP$ParserForms$stack.peek()).right;
		Object a = (Object)((java_cup.runtime.Symbol) CUP$ParserForms$stack.peek()).value;
		 RESULT = new Native(Double.parseDouble(a.toString()), new Type(TypeData.DECIMAL), aleft, aright); 
              CUP$ParserForms$result = parser.getSymbolFactory().newSymbol("valores_variables",10, ((java_cup.runtime.Symbol)CUP$ParserForms$stack.peek()), ((java_cup.runtime.Symbol)CUP$ParserForms$stack.peek()), RESULT);
            }
          return CUP$ParserForms$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 22: // valores_variables ::= ENTEROS 
            {
              Instruction RESULT =null;
		int aleft = ((java_cup.runtime.Symbol)CUP$ParserForms$stack.peek()).left;
		int aright = ((java_cup.runtime.Symbol)CUP$ParserForms$stack.peek()).right;
		Object a = (Object)((java_cup.runtime.Symbol) CUP$ParserForms$stack.peek()).value;
		 RESULT = new Native(Integer.parseInt(a.toString()), new Type(TypeData.INTEGER), aleft, aright); 
              CUP$ParserForms$result = parser.getSymbolFactory().newSymbol("valores_variables",10, ((java_cup.runtime.Symbol)CUP$ParserForms$stack.peek()), ((java_cup.runtime.Symbol)CUP$ParserForms$stack.peek()), RESULT);
            }
          return CUP$ParserForms$result;

          /* . . . . . .*/
          default:
            throw new Exception(
               "Invalid action number "+CUP$ParserForms$act_num+"found in internal parse table");

        }
    } /* end of method */

  /** Method splitting the generated action code into several parts. */
  public final java_cup.runtime.Symbol CUP$ParserForms$do_action(
    int                        CUP$ParserForms$act_num,
    java_cup.runtime.lr_parser CUP$ParserForms$parser,
    java.util.Stack            CUP$ParserForms$stack,
    int                        CUP$ParserForms$top)
    throws java.lang.Exception
    {
              return CUP$ParserForms$do_action_part00000000(
                               CUP$ParserForms$act_num,
                               CUP$ParserForms$parser,
                               CUP$ParserForms$stack,
                               CUP$ParserForms$top);
    }
}

}
