
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

package com.example.pkm_forms.Analizadores.Forms;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int HORIZONTAL = 22;
  public static final int SELECT_QUESTION = 44;
  public static final int IDENTIFICADOR = 83;
  public static final int ENTEROS = 81;
  public static final int HEXADECIMAL = 80;
  public static final int TEXT_SIZE = 31;
  public static final int DIVISION = 56;
  public static final int MENOR_QUE = 67;
  public static final int RLLAVE = 75;
  public static final int TABLE = 36;
  public static final int LLLAVE = 74;
  public static final int TEXTO = 84;
  public static final int SANS_SERIF = 29;
  public static final int DROP_QUESTION = 40;
  public static final int SPECIAL = 4;
  public static final int BLUE = 7;
  public static final int YELLOW = 11;
  public static final int DIFERENTE = 63;
  public static final int ELEMENTS = 23;
  public static final int DRAW = 5;
  public static final int WHITE = 13;
  public static final int RPAREN = 61;
  public static final int OPEN_QUESTION = 39;
  public static final int EMO_CAT = 97;
  public static final int MULTI_STAR_UNO = 85;
  public static final int BLACK = 12;
  public static final int MAYOR_QUE = 66;
  public static final int DOUBLE = 35;
  public static final int BACKGROUND_COLOR = 26;
  public static final int LPAREN = 60;
  public static final int NOT = 70;
  public static final int TEXT = 37;
  public static final int DOS_PUNTOS = 79;
  public static final int PURPLE = 9;
  public static final int WIDTH = 14;
  public static final int EMO_SMILE = 93;
  public static final int SMILE = 88;
  public static final int IGUALDAD = 62;
  public static final int STYLES = 24;
  public static final int NUMBER = 2;
  public static final int EMO_HEART = 96;
  public static final int COMA = 72;
  public static final int HEART = 91;
  public static final int MODULO = 59;
  public static final int RCORCHETE = 77;
  public static final int CURSIVE = 30;
  public static final int MONO = 28;
  public static final int IGUAL = 73;
  public static final int SAD = 89;
  public static final int WHILE = 48;
  public static final int DECIMAL = 82;
  public static final int DO = 49;
  public static final int FOR = 50;
  public static final int STAR = 87;
  public static final int ORIENTATION = 20;
  public static final int MULTI_STAR_DOS = 86;
  public static final int ELSE = 47;
  public static final int MULTIPLE_QUESTION = 45;
  public static final int CORRECT = 42;
  public static final int CONTENT = 38;
  public static final int EOF = 0;
  public static final int PUNTO = 71;
  public static final int VERTICAL = 21;
  public static final int LCORCHETE = 76;
  public static final int SUMA = 54;
  public static final int LINE = 33;
  public static final int SERIOUS = 90;
  public static final int LABEL = 16;
  public static final int MENOR_IGUAL_QUE = 65;
  public static final int IN = 51;
  public static final int OR = 69;
  public static final int SKY = 10;
  public static final int error = 1;
  public static final int RESTA = 55;
  public static final int IF = 46;
  public static final int DOTTED = 34;
  public static final int COLOR = 25;
  public static final int EMO_SAD = 94;
  public static final int UMENOS = 53;
  public static final int MULTIPLICACION = 57;
  public static final int BORDER = 32;
  public static final int HEIGHT = 15;
  public static final int RANGO = 52;
  public static final int RED = 6;
  public static final int FONT_FAMILY = 27;
  public static final int CAT = 92;
  public static final int STRING = 3;
  public static final int QUESTION_MARK = 78;
  public static final int MAYOR_IGUAL_QUE = 64;
  public static final int POINTY = 19;
  public static final int OPTIONS = 41;
  public static final int POINTX = 18;
  public static final int AND = 68;
  public static final int WHO_IS_THAT_POKEMON = 43;
  public static final int POTENCIACION = 58;
  public static final int SECTION = 17;
  public static final int GREEN = 8;
  public static final int EMO_SERIOUS = 95;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "NUMBER",
  "STRING",
  "SPECIAL",
  "DRAW",
  "RED",
  "BLUE",
  "GREEN",
  "PURPLE",
  "SKY",
  "YELLOW",
  "BLACK",
  "WHITE",
  "WIDTH",
  "HEIGHT",
  "LABEL",
  "SECTION",
  "POINTX",
  "POINTY",
  "ORIENTATION",
  "VERTICAL",
  "HORIZONTAL",
  "ELEMENTS",
  "STYLES",
  "COLOR",
  "BACKGROUND_COLOR",
  "FONT_FAMILY",
  "MONO",
  "SANS_SERIF",
  "CURSIVE",
  "TEXT_SIZE",
  "BORDER",
  "LINE",
  "DOTTED",
  "DOUBLE",
  "TABLE",
  "TEXT",
  "CONTENT",
  "OPEN_QUESTION",
  "DROP_QUESTION",
  "OPTIONS",
  "CORRECT",
  "WHO_IS_THAT_POKEMON",
  "SELECT_QUESTION",
  "MULTIPLE_QUESTION",
  "IF",
  "ELSE",
  "WHILE",
  "DO",
  "FOR",
  "IN",
  "RANGO",
  "UMENOS",
  "SUMA",
  "RESTA",
  "DIVISION",
  "MULTIPLICACION",
  "POTENCIACION",
  "MODULO",
  "LPAREN",
  "RPAREN",
  "IGUALDAD",
  "DIFERENTE",
  "MAYOR_IGUAL_QUE",
  "MENOR_IGUAL_QUE",
  "MAYOR_QUE",
  "MENOR_QUE",
  "AND",
  "OR",
  "NOT",
  "PUNTO",
  "COMA",
  "IGUAL",
  "LLLAVE",
  "RLLAVE",
  "LCORCHETE",
  "RCORCHETE",
  "QUESTION_MARK",
  "DOS_PUNTOS",
  "HEXADECIMAL",
  "ENTEROS",
  "DECIMAL",
  "IDENTIFICADOR",
  "TEXTO",
  "MULTI_STAR_UNO",
  "MULTI_STAR_DOS",
  "STAR",
  "SMILE",
  "SAD",
  "SERIOUS",
  "HEART",
  "CAT",
  "EMO_SMILE",
  "EMO_SAD",
  "EMO_SERIOUS",
  "EMO_HEART",
  "EMO_CAT"
  };
}

